name: coffee_repository

on:
  pull_request:
    paths:
      - "packages/coffee_repository/**"
      - ".github/workflows/coffee_repository.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/coffee_repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: '3.3.1'

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: packages/coffee_repository/coverage/lcov.info
